services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - ./volumes/redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
